---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.19.3
      helm:
        valueFiles:
          - $values/release/istio-ingressgateway/values.yaml

    - repoURL: https://github.com/IanHewlett/demo-platform-service-istio-system.git
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
