---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.19.3

      helm:
        valueFiles:
          - $values/release/istiod/values.yaml

    - repoURL: https://github.com/IanHewlett/demo-platform-service-istio-system.git
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
