---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-istio-csr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - chart: cert-manager-istio-csr
      repoURL: https://charts.jetstack.io
      targetRevision: 0.7.0
      helm:
        valueFiles:
          - $values/release/cert-manager-istio-csr/values.yaml

    - repoURL: https://github.com/IanHewlett/demo-platform-service-istio-system.git
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
