---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-issuer
  namespace: istio-system
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-issuer-token
  namespace: istio-system
  annotations:
    kubernetes.io/service-account.name: vault-issuer
